### ISSUE TITLE
Interface issues

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#109] opened 2016-01-07 15:12 UTC
I tested all of this yesterday morning, Wed, Jan 6 at imagecat.dyndns.org:8914 using Ubuntu 15.10 and Firefox 43.0. I had the following problems that we should work on if possible:
- the modal window still overruns, eg http://imagecat.dyndns.org:8914/#search/http%3A%2F%2Fdarpamemex%3Adarpamemex%40imagecat.dyndns.org%2Fatf%2Fallimages%2Fcom%2Fgunsinternational%2Fimages%2Fd76dfcf9704786d9a7f611e1aa3389393d118590e853c5fa3dd3c532786b4d02/make
- you can't scroll with the arrow keys when a search comes up - run a text search from the main page
- the Advanced search help blocks the search box, which makes it hard to use while crafting your own search
- on an image similarity/background/whatever search, the top menu bar wraps to two lines and screws up the formatting of the page if the page is not wide enough. On a camera make search, I had this happen all the way up to 1330px width (find an image, click the magnifying glass for a similarity search - adjust browser width)
- items in the sidebar that are removed from the homepage reappear when doing a similarity search - it is then impossible to remove them (because technically they have already been removed, but they are stuck in cache or something somewhere)
- when a modal window is opened, it should always be opened scrolled to the top, it currently seems to open scrolled to wherever the last open window was
- can we add a next button on the modal window so that you can advance through the images, perhaps in addition, we should add the match field (how the image relates to the search) into the grid view
- can we make it possible to open the modal window for an image by clicking on it when it is in the top menu bar? browsing around, I sort of got stuck with nothing on the page at one point and no obvious path back to data - I ended up just clicking the back button in order to do it, but that should be a last resort and we should avoid forcing them to do that if possible. (see http://imagecat.dyndns.org:8914/#search/http%3A%2F%2Fdarpamemex%3Adarpamemex%40imagecat.dyndns.org%2Fweapons%2Falldata%2Fcom%2Fgoogleusercontent%2Flh3%2F46A00781C17856775A20E9909E8A767BEF719E91A9379FE8204843F65716332E/cmu-background)

**Comment by danlamanna** [comment] 2016-01-07 16:00
Thanks @wmburke, we had noticed a few of these already and they were on my (mental) list. I'll be sure to go through these and ask for any clarification if necessary.

**Comment by wmburke** [comment] 2016-01-07 16:06
Cool, thanks Dan!

**Comment by danlamanna** [comment] 2016-01-07 19:38
@wmburke 

I was unable to reproduce these:
- you can't scroll with the arrow keys when a search comes up - run a text search from the main page
- items in the sidebar that are removed from the homepage reappear when doing a similarity search

Additionally, you get the most obscure bug award for the scrollbar issue: https://bugzilla.mozilla.org/show_bug.cgi?id=706792 (regardless it's been fixed on our end).

Other than that, I fixed the rest and pushed it to the dyndns machine. Give it a shot and let me know what still needs tweaking.

My only comment is in regards to the responsiveness of the header. I tweaked it a bit so it's a little better with smaller width devices, but how responsive do we want the application to be? We could potentially make it a lot better by collapsing the available searches into a dropdown at a certain width, but that's a bit more work.

**Comment by wmburke** [comment] 2016-01-07 20:10
Yay!! I won an award!! ;)

Thank you so much for your fast turnaround. Here are the results of my additional testing:
1. I believe you removed the ImageSpace "logo" from the header in addition to the gravatar. The difficulty with this is that there is now no way to return to the homepage/search box other than hitting back a bunch of times or re-entering the url. I also think we need the name of the app on every page.

As far as the gravatar, I'm cool if it is there or not, but there is also no way to know that you're logged in - and no way to log out now, as far as I can tell. Previously, you had a sub-menu with settings and log-out in it, which I think was a better solution. I think you could do the same with Help and About.

An alternative may be to keep the header as it is and just put the image specific search capabilities in a sub header.

The difficulty I was running into was yeah - the header looks ugly when it wraps, but even more importantly, the header would not push down the rest of the page, so the top of the search results, etc would get covered up. I think we could just solve that problem and then make it look intentional when it does wrap and we don't have to worry too much about it for now.

Do what you will with all of that.
1. On the arrow keys on search - here's what I did from the homepage - and it still recurs:

Enter a search query, eg "something" - when the results come up, the arrow keys don't work to scroll the page down. If I click on the page, then they do work.

If it can't be solved, it's not the end of the world for now, but let's move it into a separate issue to track it down later.
1. Similarly, I still see the issue with the images persisting in the sidebar. Maybe this will help:

from homepage with nothing in the sidebar, search for something (eg, panda).
add two images into the sidebar.
click image similarity search (magnifying glass icon) to see that the sidebar stays the same
go back to homepage, click trashcan icon to remove both images from sidebar 
search again (eg, panda)
click hour glass icon next to an image
the sidebar is there with the images still in it
clicking the trash can does nothing to remove them; reloading the page makes them go away.

I also noticed that while before the changes, the sidebar would disappear from the homepage when you deleted both images, but that doesn't happen now. The empty sidebar now persists across pages.

I hope that helps. Let me know how it looks.

**Comment by jeffbaumes** [comment] 2016-02-16 18:23
@wmburke I think this is almost all solved now - do you think we can close this and maybe make smaller issues for what's left?

**Comment by chrismattmann** [comment] 2018-04-22 16:13
fixed

**Closed as completed by chrismattmann** 2018-04-22 16:13 UTC
Labels: needs feedback
