### ISSUE TITLE
Several .js files not located when deploying image_space locally 

### ISSUE THREAD

**Issue by lewismc** [memex-explorer/image_space#65] opened 2015-07-28 20:07 UTC
When I deploy locally (build instructions are pretty much bang on, took me around 30 minutes), unfortunately when I open the main image_space app on http://localhost:8080 I get a blank screen, I also get the following screen shot.
<img width="1435" alt="screen shot 2015-07-28 at 4 04 26 pm" src="https://cloud.githubusercontent.com/assets/1165719/8942247/600cd0a0-3542-11e5-88d8-9dd6ff3fd764.png">
Only one of the three JS files is referenced within Gruntfile.js as below

```
 64         files[staticDir + '/main.min.js'] = [
 65             jsDir + '/main.js'
 66         ];
```

AFAICS the others are not listed in any other code within image_space.
This is an issue as they are referenced for import and are missing.

**Comment by chrismattmann** [comment] 2015-07-28 20:21
@lewismc i'm not able to reproduce this, but one of the keys is that your imagespace.min didn't work. My thoughts are that the python you are using is messing up on the hack-around for Grunt that we did with imagespace to convert JS and Python dicts to one another. You may need to hack the Gruntfile.js (look up the python part, and then make sure that it's actually running against a 2.7 or later python which that python snippet depends on). Then re-run grunt from the girder main area and see if you get imagespace.min.\* cc @jeffbaumes

**Comment by jeffbaumes** [comment] 2015-07-28 20:37
Talked with @lewismc just now. This particular issue was resolved by re-running grunt. @lewismc will look into updating the README to make this more clear.

**Comment by chrismattmann** [comment] 2015-07-28 20:40
cool thanks @jeffbaumes was it the Python issue I described? I ran into that, the params.py hack in Gruntfile.js only works on Python 2.7+ or newer, so on systems where that isn't the case, there is a problem

**Closed as completed** 2015-07-30 01:26 UTC
